### ISSUE TITLE
Unable to build under windows

### ISSUE THREAD

**Issue by adimkov** [lastfm/Fingerprinter#4]
Unfortunately build fails under windows. Could you share already built binaries?
 thank you

**Comment by evilrix** [comment]
Unfortunately, we don't maintain a specific Windows build as our development infrastructure is all Linux/Mac. That said, it should build under Windows as it's all ANSI standard complient code. You just need to ensure you have all the correct libraries install/available. Unfortunately, we don't have pre-built libraries because Windows isn't a platform we specifically target. Sorry. If you can tell me what errors you are seeing I might be able to advise on how you might fix it (and in return, if there is a problem that needs fixing we'd appreciate a pull request if you fix it).
